name: config_builder_example
description: Build your app config via code gen from .env files
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:


dev_dependencies:
  build_runner: ^1.10.3
  config_builder:
    path: ../

