name: config_builder_example
description: Build your app config via code gen from .env files
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
   config_builder:
     path: ../

dev_dependencies:
  build_runner: ^1.6.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

