name: config_builder_example
description: Build your app config via code gen from .env files
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:


dev_dependencies:
  build_runner: ^2.0.0
  config_builder:
    path: ../

