name: config_builder
description: Build your app config via code generation from .json files in a type safe way
version: 0.4.0+1
author: Martin Kamleithner <martin.kamleithner@gmail.com>
homepage: https://github.com/knaeckeKami/config_builder

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  source_gen: ^0.9.4+7
  analyzer: ^0.39.2+1
  build: ^1.2.2

dev_dependencies:

