name: config_builder
description: Build your app config via code generation from .json files in a type safe way
version: 0.3.0
author: Martin Kamleithner <martin.kamleithner@gmail.com>
homepage: https://github.com/knaeckeKami/config_builder

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  source_gen: ^0.9.4+6
  analyzer: ^0.38.0
  build: ^1.2.1

dev_dependencies:

