name: config_builder
description: Build your app config via code generation from .json files in a type safe way
version: 1.1.0
author: Martin Kamleithner <martin.kamleithner@gmail.com>
homepage: https://github.com/knaeckeKami/config_builder

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  source_gen: ^0.9.7+1
  analyzer: ^0.40.4
  build: ^1.5.0
  glob: ^1.2.0

dev_dependencies:

